[mypy]
check_untyped_defs = True
warn_return_any = True

[mypy-connectrpc.*]
ignore_missing_imports = True

[mypy-pylabrobot.*]
ignore_missing_imports = True

[mypy-google.protobuf.*]
ignore_missing_imports = True

[mypy-pylabrobot_protobuf_client.*]
ignore_missing_imports = True
