# mypy: disable-error-code="no-any-return"
"""ConnectRPC service stubs for LiquidHandlerService.

Hand-written to match the pattern generated by protoc-gen-connect-python.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.server import (
  ConnectASGIApplication,
  Endpoint,
)

from . import liquid_handler_service_pb2 as pb2
from . import types_pb2

if TYPE_CHECKING:
  from collections.abc import AsyncGenerator, Iterable, Mapping

  from connectrpc.interceptor import Interceptor
  from connectrpc.request import Headers, RequestContext


_SVC = "pylabrobot.liquid_handler.v1.LiquidHandlerService"


def _method(
  name: str,
  input_cls: type,
  output_cls: type,
  idempotency: IdempotencyLevel = IdempotencyLevel.UNKNOWN,
) -> MethodInfo:
  return MethodInfo(
    name=name, service_name=_SVC, input=input_cls, output=output_cls, idempotency_level=idempotency
  )


# All read-only RPCs use NO_SIDE_EFFECTS for idempotency.
_NS = IdempotencyLevel.NO_SIDE_EFFECTS

# ============================================================
# Method descriptors
# ============================================================

# Single-channel tips
_PICK_UP_TIPS = _method("PickUpTips", pb2.PickUpTipsRequest, types_pb2.Empty)
_DROP_TIPS = _method("DropTips", pb2.DropTipsRequest, types_pb2.Empty)
_RETURN_TIPS = _method("ReturnTips", pb2.ReturnTipsRequest, types_pb2.Empty)
_DISCARD_TIPS = _method("DiscardTips", pb2.DiscardTipsRequest, types_pb2.Empty)

# Single-channel liquid
_ASPIRATE = _method("Aspirate", pb2.AspirateRequest, types_pb2.Empty)
_DISPENSE = _method("Dispense", pb2.DispenseRequest, types_pb2.Empty)

# 96-head tips
_PICK_UP_TIPS96 = _method("PickUpTips96", pb2.PickUpTips96Request, types_pb2.Empty)
_DROP_TIPS96 = _method("DropTips96", pb2.DropTips96Request, types_pb2.Empty)
_RETURN_TIPS96 = _method("ReturnTips96", pb2.ReturnTips96Request, types_pb2.Empty)
_DISCARD_TIPS96 = _method("DiscardTips96", pb2.DiscardTips96Request, types_pb2.Empty)

# 96-head liquid
_ASPIRATE96 = _method("Aspirate96", pb2.Aspirate96Request, types_pb2.Empty)
_DISPENSE96 = _method("Dispense96", pb2.Dispense96Request, types_pb2.Empty)

# Resource movement (high-level)
_MOVE_RESOURCE = _method("MoveResource", pb2.MoveResourceRequest, types_pb2.Empty)
_MOVE_PLATE = _method("MovePlate", pb2.MovePlateRequest, types_pb2.Empty)
_MOVE_LID = _method("MoveLid", pb2.MoveLidRequest, types_pb2.Empty)

# Resource movement (low-level)
_PICK_UP_RESOURCE = _method("PickUpResource", pb2.PickUpResourceRequest, types_pb2.Empty)
_MOVE_PICKED_UP_RESOURCE = _method(
  "MovePickedUpResource", pb2.MovePickedUpResourceRequest, types_pb2.Empty
)
_DROP_RESOURCE = _method("DropResource", pb2.DropResourceRequest, types_pb2.Empty)

# State queries
_GET_MOUNTED_TIPS = _method("GetMountedTips", types_pb2.Empty, pb2.GetMountedTipsResponse, _NS)
_GET_PICKED_UP_RESOURCE = _method(
  "GetPickedUpResource", types_pb2.Empty, pb2.GetPickedUpResourceResponse, _NS
)


# ============================================================
# Async service protocol
# ============================================================


class LiquidHandlerService(Protocol):
  # --- Single-channel tips ---

  async def pick_up_tips(self, request: pb2.PickUpTipsRequest, ctx: RequestContext) -> types_pb2.Empty:
    raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

  async def drop_tips(self, request: pb2.DropTipsRequest, ctx: RequestContext) -> types_pb2.Empty:
    raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

  async def return_tips(self, request: pb2.ReturnTipsRequest, ctx: RequestContext) -> types_pb2.Empty:
    raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

  async def discard_tips(self, request: pb2.DiscardTipsRequest, ctx: RequestContext) -> types_pb2.Empty:
    raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

  # --- Single-channel liquid ---

  async def aspirate(self, request: pb2.AspirateRequest, ctx: RequestContext) -> types_pb2.Empty:
    raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

  async def dispense(self, request: pb2.DispenseRequest, ctx: RequestContext) -> types_pb2.Empty:
    raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

  # --- 96-head tips ---

  async def pick_up_tips96(
    self, request: pb2.PickUpTips96Request, ctx: RequestContext
  ) -> types_pb2.Empty:
    raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

  async def drop_tips96(self, request: pb2.DropTips96Request, ctx: RequestContext) -> types_pb2.Empty:
    raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

  async def return_tips96(
    self, request: pb2.ReturnTips96Request, ctx: RequestContext
  ) -> types_pb2.Empty:
    raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

  async def discard_tips96(
    self, request: pb2.DiscardTips96Request, ctx: RequestContext
  ) -> types_pb2.Empty:
    raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

  # --- 96-head liquid ---

  async def aspirate96(self, request: pb2.Aspirate96Request, ctx: RequestContext) -> types_pb2.Empty:
    raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

  async def dispense96(self, request: pb2.Dispense96Request, ctx: RequestContext) -> types_pb2.Empty:
    raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

  # --- Resource movement (high-level) ---

  async def move_resource(
    self, request: pb2.MoveResourceRequest, ctx: RequestContext
  ) -> types_pb2.Empty:
    raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

  async def move_plate(self, request: pb2.MovePlateRequest, ctx: RequestContext) -> types_pb2.Empty:
    raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

  async def move_lid(self, request: pb2.MoveLidRequest, ctx: RequestContext) -> types_pb2.Empty:
    raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

  # --- Resource movement (low-level) ---

  async def pick_up_resource(
    self, request: pb2.PickUpResourceRequest, ctx: RequestContext
  ) -> types_pb2.Empty:
    raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

  async def move_picked_up_resource(
    self, request: pb2.MovePickedUpResourceRequest, ctx: RequestContext
  ) -> types_pb2.Empty:
    raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

  async def drop_resource(
    self, request: pb2.DropResourceRequest, ctx: RequestContext
  ) -> types_pb2.Empty:
    raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

  # --- State queries ---

  async def get_mounted_tips(
    self, request: types_pb2.Empty, ctx: RequestContext
  ) -> pb2.GetMountedTipsResponse:
    raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

  async def get_picked_up_resource(
    self, request: types_pb2.Empty, ctx: RequestContext
  ) -> pb2.GetPickedUpResourceResponse:
    raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


# ============================================================
# ASGI application
# ============================================================


class LiquidHandlerServiceASGIApplication(ConnectASGIApplication[LiquidHandlerService]):
  def __init__(
    self,
    service: LiquidHandlerService | AsyncGenerator[LiquidHandlerService],
    *,
    interceptors: Iterable[Interceptor] = (),
    read_max_bytes: int | None = None,
  ) -> None:
    super().__init__(
      service=service,
      endpoints=lambda svc: {
        # Single-channel tips
        f"/{_SVC}/PickUpTips": Endpoint.unary(method=_PICK_UP_TIPS, function=svc.pick_up_tips),
        f"/{_SVC}/DropTips": Endpoint.unary(method=_DROP_TIPS, function=svc.drop_tips),
        f"/{_SVC}/ReturnTips": Endpoint.unary(method=_RETURN_TIPS, function=svc.return_tips),
        f"/{_SVC}/DiscardTips": Endpoint.unary(method=_DISCARD_TIPS, function=svc.discard_tips),
        # Single-channel liquid
        f"/{_SVC}/Aspirate": Endpoint.unary(method=_ASPIRATE, function=svc.aspirate),
        f"/{_SVC}/Dispense": Endpoint.unary(method=_DISPENSE, function=svc.dispense),
        # 96-head tips
        f"/{_SVC}/PickUpTips96": Endpoint.unary(
          method=_PICK_UP_TIPS96, function=svc.pick_up_tips96
        ),
        f"/{_SVC}/DropTips96": Endpoint.unary(method=_DROP_TIPS96, function=svc.drop_tips96),
        f"/{_SVC}/ReturnTips96": Endpoint.unary(
          method=_RETURN_TIPS96, function=svc.return_tips96
        ),
        f"/{_SVC}/DiscardTips96": Endpoint.unary(
          method=_DISCARD_TIPS96, function=svc.discard_tips96
        ),
        # 96-head liquid
        f"/{_SVC}/Aspirate96": Endpoint.unary(method=_ASPIRATE96, function=svc.aspirate96),
        f"/{_SVC}/Dispense96": Endpoint.unary(method=_DISPENSE96, function=svc.dispense96),
        # Resource movement (high-level)
        f"/{_SVC}/MoveResource": Endpoint.unary(
          method=_MOVE_RESOURCE, function=svc.move_resource
        ),
        f"/{_SVC}/MovePlate": Endpoint.unary(method=_MOVE_PLATE, function=svc.move_plate),
        f"/{_SVC}/MoveLid": Endpoint.unary(method=_MOVE_LID, function=svc.move_lid),
        # Resource movement (low-level)
        f"/{_SVC}/PickUpResource": Endpoint.unary(
          method=_PICK_UP_RESOURCE, function=svc.pick_up_resource
        ),
        f"/{_SVC}/MovePickedUpResource": Endpoint.unary(
          method=_MOVE_PICKED_UP_RESOURCE, function=svc.move_picked_up_resource
        ),
        f"/{_SVC}/DropResource": Endpoint.unary(
          method=_DROP_RESOURCE, function=svc.drop_resource
        ),
        # State queries
        f"/{_SVC}/GetMountedTips": Endpoint.unary(
          method=_GET_MOUNTED_TIPS, function=svc.get_mounted_tips
        ),
        f"/{_SVC}/GetPickedUpResource": Endpoint.unary(
          method=_GET_PICKED_UP_RESOURCE, function=svc.get_picked_up_resource
        ),
      },
      interceptors=interceptors,
      read_max_bytes=read_max_bytes,
    )

  @property
  def path(self) -> str:
    return f"/{_SVC}"


# ============================================================
# Async client
# ============================================================


class LiquidHandlerServiceClient(ConnectClient):
  # --- Single-channel tips ---

  async def pick_up_tips(
    self,
    request: pb2.PickUpTipsRequest,
    *,
    headers: Headers | Mapping[str, str] | None = None,
    timeout_ms: int | None = None,
  ) -> types_pb2.Empty:
    return await self.execute_unary(
      request=request, method=_PICK_UP_TIPS, headers=headers, timeout_ms=timeout_ms
    )

  async def drop_tips(
    self,
    request: pb2.DropTipsRequest,
    *,
    headers: Headers | Mapping[str, str] | None = None,
    timeout_ms: int | None = None,
  ) -> types_pb2.Empty:
    return await self.execute_unary(
      request=request, method=_DROP_TIPS, headers=headers, timeout_ms=timeout_ms
    )

  async def return_tips(
    self,
    request: pb2.ReturnTipsRequest,
    *,
    headers: Headers | Mapping[str, str] | None = None,
    timeout_ms: int | None = None,
  ) -> types_pb2.Empty:
    return await self.execute_unary(
      request=request, method=_RETURN_TIPS, headers=headers, timeout_ms=timeout_ms
    )

  async def discard_tips(
    self,
    request: pb2.DiscardTipsRequest,
    *,
    headers: Headers | Mapping[str, str] | None = None,
    timeout_ms: int | None = None,
  ) -> types_pb2.Empty:
    return await self.execute_unary(
      request=request, method=_DISCARD_TIPS, headers=headers, timeout_ms=timeout_ms
    )

  # --- Single-channel liquid ---

  async def aspirate(
    self,
    request: pb2.AspirateRequest,
    *,
    headers: Headers | Mapping[str, str] | None = None,
    timeout_ms: int | None = None,
  ) -> types_pb2.Empty:
    return await self.execute_unary(
      request=request, method=_ASPIRATE, headers=headers, timeout_ms=timeout_ms
    )

  async def dispense(
    self,
    request: pb2.DispenseRequest,
    *,
    headers: Headers | Mapping[str, str] | None = None,
    timeout_ms: int | None = None,
  ) -> types_pb2.Empty:
    return await self.execute_unary(
      request=request, method=_DISPENSE, headers=headers, timeout_ms=timeout_ms
    )

  # --- 96-head tips ---

  async def pick_up_tips96(
    self,
    request: pb2.PickUpTips96Request,
    *,
    headers: Headers | Mapping[str, str] | None = None,
    timeout_ms: int | None = None,
  ) -> types_pb2.Empty:
    return await self.execute_unary(
      request=request, method=_PICK_UP_TIPS96, headers=headers, timeout_ms=timeout_ms
    )

  async def drop_tips96(
    self,
    request: pb2.DropTips96Request,
    *,
    headers: Headers | Mapping[str, str] | None = None,
    timeout_ms: int | None = None,
  ) -> types_pb2.Empty:
    return await self.execute_unary(
      request=request, method=_DROP_TIPS96, headers=headers, timeout_ms=timeout_ms
    )

  async def return_tips96(
    self,
    request: pb2.ReturnTips96Request,
    *,
    headers: Headers | Mapping[str, str] | None = None,
    timeout_ms: int | None = None,
  ) -> types_pb2.Empty:
    return await self.execute_unary(
      request=request, method=_RETURN_TIPS96, headers=headers, timeout_ms=timeout_ms
    )

  async def discard_tips96(
    self,
    request: pb2.DiscardTips96Request,
    *,
    headers: Headers | Mapping[str, str] | None = None,
    timeout_ms: int | None = None,
  ) -> types_pb2.Empty:
    return await self.execute_unary(
      request=request, method=_DISCARD_TIPS96, headers=headers, timeout_ms=timeout_ms
    )

  # --- 96-head liquid ---

  async def aspirate96(
    self,
    request: pb2.Aspirate96Request,
    *,
    headers: Headers | Mapping[str, str] | None = None,
    timeout_ms: int | None = None,
  ) -> types_pb2.Empty:
    return await self.execute_unary(
      request=request, method=_ASPIRATE96, headers=headers, timeout_ms=timeout_ms
    )

  async def dispense96(
    self,
    request: pb2.Dispense96Request,
    *,
    headers: Headers | Mapping[str, str] | None = None,
    timeout_ms: int | None = None,
  ) -> types_pb2.Empty:
    return await self.execute_unary(
      request=request, method=_DISPENSE96, headers=headers, timeout_ms=timeout_ms
    )

  # --- Resource movement (high-level) ---

  async def move_resource(
    self,
    request: pb2.MoveResourceRequest,
    *,
    headers: Headers | Mapping[str, str] | None = None,
    timeout_ms: int | None = None,
  ) -> types_pb2.Empty:
    return await self.execute_unary(
      request=request, method=_MOVE_RESOURCE, headers=headers, timeout_ms=timeout_ms
    )

  async def move_plate(
    self,
    request: pb2.MovePlateRequest,
    *,
    headers: Headers | Mapping[str, str] | None = None,
    timeout_ms: int | None = None,
  ) -> types_pb2.Empty:
    return await self.execute_unary(
      request=request, method=_MOVE_PLATE, headers=headers, timeout_ms=timeout_ms
    )

  async def move_lid(
    self,
    request: pb2.MoveLidRequest,
    *,
    headers: Headers | Mapping[str, str] | None = None,
    timeout_ms: int | None = None,
  ) -> types_pb2.Empty:
    return await self.execute_unary(
      request=request, method=_MOVE_LID, headers=headers, timeout_ms=timeout_ms
    )

  # --- Resource movement (low-level) ---

  async def pick_up_resource(
    self,
    request: pb2.PickUpResourceRequest,
    *,
    headers: Headers | Mapping[str, str] | None = None,
    timeout_ms: int | None = None,
  ) -> types_pb2.Empty:
    return await self.execute_unary(
      request=request, method=_PICK_UP_RESOURCE, headers=headers, timeout_ms=timeout_ms
    )

  async def move_picked_up_resource(
    self,
    request: pb2.MovePickedUpResourceRequest,
    *,
    headers: Headers | Mapping[str, str] | None = None,
    timeout_ms: int | None = None,
  ) -> types_pb2.Empty:
    return await self.execute_unary(
      request=request, method=_MOVE_PICKED_UP_RESOURCE, headers=headers, timeout_ms=timeout_ms
    )

  async def drop_resource(
    self,
    request: pb2.DropResourceRequest,
    *,
    headers: Headers | Mapping[str, str] | None = None,
    timeout_ms: int | None = None,
  ) -> types_pb2.Empty:
    return await self.execute_unary(
      request=request, method=_DROP_RESOURCE, headers=headers, timeout_ms=timeout_ms
    )

  # --- State queries ---

  async def get_mounted_tips(
    self,
    request: types_pb2.Empty,
    *,
    headers: Headers | Mapping[str, str] | None = None,
    timeout_ms: int | None = None,
    use_get: bool = False,
  ) -> pb2.GetMountedTipsResponse:
    return await self.execute_unary(
      request=request,
      method=_GET_MOUNTED_TIPS,
      headers=headers,
      timeout_ms=timeout_ms,
      use_get=use_get,
    )

  async def get_picked_up_resource(
    self,
    request: types_pb2.Empty,
    *,
    headers: Headers | Mapping[str, str] | None = None,
    timeout_ms: int | None = None,
    use_get: bool = False,
  ) -> pb2.GetPickedUpResourceResponse:
    return await self.execute_unary(
      request=request,
      method=_GET_PICKED_UP_RESOURCE,
      headers=headers,
      timeout_ms=timeout_ms,
      use_get=use_get,
    )


# ============================================================
# Sync client
# ============================================================


class LiquidHandlerServiceClientSync(ConnectClientSync):
  # --- Single-channel tips ---

  def pick_up_tips(
    self,
    request: pb2.PickUpTipsRequest,
    *,
    headers: Headers | Mapping[str, str] | None = None,
    timeout_ms: int | None = None,
  ) -> types_pb2.Empty:
    return self.execute_unary(
      request=request, method=_PICK_UP_TIPS, headers=headers, timeout_ms=timeout_ms
    )

  def drop_tips(
    self,
    request: pb2.DropTipsRequest,
    *,
    headers: Headers | Mapping[str, str] | None = None,
    timeout_ms: int | None = None,
  ) -> types_pb2.Empty:
    return self.execute_unary(
      request=request, method=_DROP_TIPS, headers=headers, timeout_ms=timeout_ms
    )

  def return_tips(
    self,
    request: pb2.ReturnTipsRequest,
    *,
    headers: Headers | Mapping[str, str] | None = None,
    timeout_ms: int | None = None,
  ) -> types_pb2.Empty:
    return self.execute_unary(
      request=request, method=_RETURN_TIPS, headers=headers, timeout_ms=timeout_ms
    )

  def discard_tips(
    self,
    request: pb2.DiscardTipsRequest,
    *,
    headers: Headers | Mapping[str, str] | None = None,
    timeout_ms: int | None = None,
  ) -> types_pb2.Empty:
    return self.execute_unary(
      request=request, method=_DISCARD_TIPS, headers=headers, timeout_ms=timeout_ms
    )

  # --- Single-channel liquid ---

  def aspirate(
    self,
    request: pb2.AspirateRequest,
    *,
    headers: Headers | Mapping[str, str] | None = None,
    timeout_ms: int | None = None,
  ) -> types_pb2.Empty:
    return self.execute_unary(
      request=request, method=_ASPIRATE, headers=headers, timeout_ms=timeout_ms
    )

  def dispense(
    self,
    request: pb2.DispenseRequest,
    *,
    headers: Headers | Mapping[str, str] | None = None,
    timeout_ms: int | None = None,
  ) -> types_pb2.Empty:
    return self.execute_unary(
      request=request, method=_DISPENSE, headers=headers, timeout_ms=timeout_ms
    )

  # --- 96-head tips ---

  def pick_up_tips96(
    self,
    request: pb2.PickUpTips96Request,
    *,
    headers: Headers | Mapping[str, str] | None = None,
    timeout_ms: int | None = None,
  ) -> types_pb2.Empty:
    return self.execute_unary(
      request=request, method=_PICK_UP_TIPS96, headers=headers, timeout_ms=timeout_ms
    )

  def drop_tips96(
    self,
    request: pb2.DropTips96Request,
    *,
    headers: Headers | Mapping[str, str] | None = None,
    timeout_ms: int | None = None,
  ) -> types_pb2.Empty:
    return self.execute_unary(
      request=request, method=_DROP_TIPS96, headers=headers, timeout_ms=timeout_ms
    )

  def return_tips96(
    self,
    request: pb2.ReturnTips96Request,
    *,
    headers: Headers | Mapping[str, str] | None = None,
    timeout_ms: int | None = None,
  ) -> types_pb2.Empty:
    return self.execute_unary(
      request=request, method=_RETURN_TIPS96, headers=headers, timeout_ms=timeout_ms
    )

  def discard_tips96(
    self,
    request: pb2.DiscardTips96Request,
    *,
    headers: Headers | Mapping[str, str] | None = None,
    timeout_ms: int | None = None,
  ) -> types_pb2.Empty:
    return self.execute_unary(
      request=request, method=_DISCARD_TIPS96, headers=headers, timeout_ms=timeout_ms
    )

  # --- 96-head liquid ---

  def aspirate96(
    self,
    request: pb2.Aspirate96Request,
    *,
    headers: Headers | Mapping[str, str] | None = None,
    timeout_ms: int | None = None,
  ) -> types_pb2.Empty:
    return self.execute_unary(
      request=request, method=_ASPIRATE96, headers=headers, timeout_ms=timeout_ms
    )

  def dispense96(
    self,
    request: pb2.Dispense96Request,
    *,
    headers: Headers | Mapping[str, str] | None = None,
    timeout_ms: int | None = None,
  ) -> types_pb2.Empty:
    return self.execute_unary(
      request=request, method=_DISPENSE96, headers=headers, timeout_ms=timeout_ms
    )

  # --- Resource movement (high-level) ---

  def move_resource(
    self,
    request: pb2.MoveResourceRequest,
    *,
    headers: Headers | Mapping[str, str] | None = None,
    timeout_ms: int | None = None,
  ) -> types_pb2.Empty:
    return self.execute_unary(
      request=request, method=_MOVE_RESOURCE, headers=headers, timeout_ms=timeout_ms
    )

  def move_plate(
    self,
    request: pb2.MovePlateRequest,
    *,
    headers: Headers | Mapping[str, str] | None = None,
    timeout_ms: int | None = None,
  ) -> types_pb2.Empty:
    return self.execute_unary(
      request=request, method=_MOVE_PLATE, headers=headers, timeout_ms=timeout_ms
    )

  def move_lid(
    self,
    request: pb2.MoveLidRequest,
    *,
    headers: Headers | Mapping[str, str] | None = None,
    timeout_ms: int | None = None,
  ) -> types_pb2.Empty:
    return self.execute_unary(
      request=request, method=_MOVE_LID, headers=headers, timeout_ms=timeout_ms
    )

  # --- Resource movement (low-level) ---

  def pick_up_resource(
    self,
    request: pb2.PickUpResourceRequest,
    *,
    headers: Headers | Mapping[str, str] | None = None,
    timeout_ms: int | None = None,
  ) -> types_pb2.Empty:
    return self.execute_unary(
      request=request, method=_PICK_UP_RESOURCE, headers=headers, timeout_ms=timeout_ms
    )

  def move_picked_up_resource(
    self,
    request: pb2.MovePickedUpResourceRequest,
    *,
    headers: Headers | Mapping[str, str] | None = None,
    timeout_ms: int | None = None,
  ) -> types_pb2.Empty:
    return self.execute_unary(
      request=request, method=_MOVE_PICKED_UP_RESOURCE, headers=headers, timeout_ms=timeout_ms
    )

  def drop_resource(
    self,
    request: pb2.DropResourceRequest,
    *,
    headers: Headers | Mapping[str, str] | None = None,
    timeout_ms: int | None = None,
  ) -> types_pb2.Empty:
    return self.execute_unary(
      request=request, method=_DROP_RESOURCE, headers=headers, timeout_ms=timeout_ms
    )

  # --- State queries ---

  def get_mounted_tips(
    self,
    request: types_pb2.Empty,
    *,
    headers: Headers | Mapping[str, str] | None = None,
    timeout_ms: int | None = None,
    use_get: bool = False,
  ) -> pb2.GetMountedTipsResponse:
    return self.execute_unary(
      request=request,
      method=_GET_MOUNTED_TIPS,
      headers=headers,
      timeout_ms=timeout_ms,
      use_get=use_get,
    )

  def get_picked_up_resource(
    self,
    request: types_pb2.Empty,
    *,
    headers: Headers | Mapping[str, str] | None = None,
    timeout_ms: int | None = None,
    use_get: bool = False,
  ) -> pb2.GetPickedUpResourceResponse:
    return self.execute_unary(
      request=request,
      method=_GET_PICKED_UP_RESOURCE,
      headers=headers,
      timeout_ms=timeout_ms,
      use_get=use_get,
    )
